### PR TITLE
feat(docs): add faq

### LINKED ISSUE #82: feat(docs): add faq
Adding a FAQ to the documentation would reduce the time spent on helping with redundant questions.

If you have an idea but don't feel like writing an answer right now feel free to drop it here and someone else might already do it in the meantime.

### PR DESCRIPTION
**Pull request by owittek**
Resolves #82

### CODE REVIEW

**Comment by Uzaaft** [comment]
How about a section about: "Astronvim is slow!" ? Where we go trough common issues etc? Like issues with fish, WSL, etc

**Comment by owittek** [comment]
> How about a section about: "Astronvim is slow!" ? Where we go trough common issues etc? Like issues with fish, WSL, etc

sounds good to me!

**Review by mehalter — APPROVED** [review]
Looks great! I did some cleanup and also went ahead and updated our npm packages. Once the tests pass and we verify the page looks correct on the test deployment I think we can go ahead and merge this!

**Comment by owittek** [comment]
I went through your cleanup, looks great!

**Comment by mehalter** [comment]
Cool merged @owittek I need to spend some time adding some new bindings that were added in v3.15 and things to update our documentation and then I can tag a new release for the docs which will include the FAQ

**Pull request merged**
