### PR TITLE
Fix deprecated autocmds

### PR DESCRIPTION
**Pull request by cusxio**
https://github.com/AstroNvim/AstroNvim/commit/74577e510d62840861ae3d4e03bba6d4a8864a29

### CODE REVIEW

**Comment by mehalter** [comment]
This is incorrect, that commit *fixed* the AstroLspSetup event

**Comment by cusxio** [comment]
I don't think so, at least in v3.0.3. I used the config listed in https://astronvim.com/Recipes/advanced_lsp#typescript-typescriptnvim, but it doesn't work, only after I changed it to `AstroMasonLspSetup` did it work.

**Comment by mehalter** [comment]
I'll take a look soon to see what's going on, but it should be fixed I suppose 😂

**Comment by mehalter** [comment]
@cusxio I verified that this autocmd event is working as intended. The weirdness is coming from how neovim deals with filetypes and calls filetype which is what triggers `lspconfig` to check for servers to auto start. I have just in general updated that section of recipes to be a little more sane, more stable, make more sense, and will be a bit more performant: https://astronvim.com/Recipes/advanced_lsp#lsp-specific-plugins

In general this approach that I have updated them to is a much better approach

**Pull request closed without merging**
